
POST http://localhost:8800/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "accountName": "a1@gmail.com", 
    "password": "12345678", 
    "typeAccount": "A1",
    "providerAccount": "61ab69a480482f0d9c708ba4"
}


###
POST http://localhost:8800/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "trung@gmail.com",
    "password": "12345678",
    "position": "admin"
}


###
GET http://localhost:8800/api/getuser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTk3OTE2NjAwMTY0N2Q0YjA5OTU2MjIiLCJpYXQiOjE2MzczMjQxOTF9.2BUoXQRSP-UQr4KFDQHyfC46vlnWmz7L8hoElLUERRU



###
GET https://8800-coffee-sheep-v40f6imz.ws-us21.gitpod.io//students HTTP/1.1